# Generated by Django 5.1.15 on 2026-02-16 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('upcoming_event', 'Upcoming Event'), ('equipment_due_return', 'Equipment Due Return'), ('repair_completed', 'Repair Completed'), ('pending_confirmation', 'Pending Confirmation'), ('schedule_changed', 'Schedule Changed'), ('fault_reported', 'Fault Reported'), ('rental_expiring', 'Rental Expiring'), ('equipment_transferred', 'Equipment Transferred'), ('equipment_conflict', 'Equipment Conflict'), ('system', 'System')], max_length=30)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email')], max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'event_type'], name='notificatio_user_id_1cf151_idx')],
                'unique_together': {('user', 'event_type', 'channel')},
            },
        ),
    ]
