# Generated by Django 5.1.15 on 2026-02-15 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('rentals', '0002_rentalagreementline_rentalagreement_agreement_number_and_more'),
        ('schedules', '0002_checkoutrecord_scheduleequipment_schedulestatuslog_and_more'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition_on_return', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='status',
            field=models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=25),
        ),
        migrations.AddConstraint(
            model_name='warehousetransaction',
            constraint=models.CheckConstraint(condition=models.Q(('rental_agreement__isnull', False), ('schedule__isnull', False), _negated=True), name='wt_schedule_rental_mutually_exclusive'),
        ),
        migrations.AddField(
            model_name='transactionlineitem',
            name='equipment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_line_items', to='equipment.equipmentitem'),
        ),
        migrations.AddField(
            model_name='transactionlineitem',
            name='equipment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_line_items', to='equipment.equipmentmodel'),
        ),
        migrations.AddField(
            model_name='transactionlineitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='warehouse.warehousetransaction'),
        ),
    ]
