# Generated by Django 5.1.15 on 2026-02-15 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        ('schedules', '0001_initial'),
        ('transfers', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='equipment.equipmentcategory')),
            ],
            options={
                'verbose_name_plural': 'equipment categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_numbered', models.BooleanField(default=True, help_text='If False, tracked by quantity only (e.g., cables).')),
                ('total_quantity', models.PositiveIntegerField(default=0, help_text='For unnumbered equipment only.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/models/')),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_models', to='equipment.equipmentcategory')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('internal_id', models.CharField(blank=True, help_text='Internal company identifier.', max_length=100)),
                ('ownership_type', models.CharField(choices=[('owned', 'Owned'), ('rented_in', 'Rented In')], default='owned', max_length=20)),
                ('current_status', models.CharField(choices=[('pending_receipt', 'Pending Receipt'), ('available', 'Available'), ('out', 'Out'), ('reserved', 'Reserved'), ('lost', 'Lost'), ('retired', 'Retired'), ('returned_to_vendor', 'Returned to Vendor')], default='available', help_text='Denormalized cache. EquipmentStatusLog is source of truth.', max_length=30)),
                ('lamp_hours', models.PositiveIntegerField(default=0)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('rental_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='rentals.rentalagreement')),
                ('equipment_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='equipment.equipmentmodel')),
            ],
            options={
                'ordering': ['equipment_model', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('check_out', 'Check Out'), ('check_in', 'Check In'), ('transfer', 'Transfer'), ('register', 'Register'), ('deregister', 'Deregister'), ('reserve', 'Reserve'), ('unreserve', 'Unreserve'), ('mark_lost', 'Mark Lost'), ('mark_retired', 'Mark Retired'), ('reconcile', 'Reconcile')], max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('equipment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='equipment.equipmentitem')),
                ('equipment_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_status_logs', to='transfers.equipmenttransfer')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_status_changes', to=settings.AUTH_USER_MODEL)),
                ('rental_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_status_logs', to='rentals.rentalagreement')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_status_logs', to='schedules.schedule')),
                ('warehouse_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_status_logs', to='warehouse.warehousetransaction')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='FaultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('equipment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_records', to='equipment.equipmentitem')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_faults', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_faults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['category', 'is_active'], name='equipment_e_categor_8d0c54_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentitem',
            index=models.Index(fields=['equipment_model', 'current_status'], name='equipment_e_equipme_7e6227_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentitem',
            index=models.Index(fields=['current_status'], name='equipment_e_current_2af74d_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ownership_type', 'owned'), ('rental_agreement__isnull', True)), models.Q(('ownership_type', 'rented_in'), ('rental_agreement__isnull', False)), _connector='OR'), name='rental_agreement_consistency'),
        ),
        migrations.AddIndex(
            model_name='equipmentstatuslog',
            index=models.Index(fields=['equipment_item', '-performed_at'], name='equipment_e_equipme_d62415_idx'),
        ),
    ]
