# Generated by Django 5.1.15 on 2026-02-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_internal_id_unique_constraint'),
        ('rentals', '0002_rentalagreementline_rentalagreement_agreement_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentitem',
            options={'ordering': ['equipment_model', 'internal_id']},
        ),
        migrations.RemoveConstraint(
            model_name='equipmentitem',
            name='uniq_equipment_model_internal_id',
        ),
        migrations.AddConstraint(
            model_name='equipmentitem',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_id', ''), _negated=True), fields=('equipment_model', 'internal_id'), name='uniq_equipment_model_internal_id'),
        ),
    ]
