# Generated by Django 5.1.15 on 2026-02-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipmentitem_options_and_more'),
        ('rentals', '0002_rentalagreementline_rentalagreement_agreement_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipmentitem',
            name='uniq_equipment_model_internal_id',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='internal_id',
            field=models.CharField(help_text='Internal company identifier.', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='equipmentitem',
            constraint=models.UniqueConstraint(fields=('equipment_model', 'internal_id'), name='uniq_equipment_model_internal_id'),
        ),
    ]
