# Generated by Django 5.1.15 on 2026-02-15 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('user_display', models.CharField(help_text='Denormalized display name at time of action', max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('schedule', 'Schedule'), ('warehouse', 'Warehouse'), ('rental', 'Rental'), ('transfer', 'Transfer'), ('user', 'User')], max_length=20)),
                ('description', models.TextField()),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('entity_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('entity_display', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['category', '-created_at'], name='audit_audit_categor_529cbb_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['entity_type', 'entity_uuid'], name='audit_audit_entity__100fa0_idx')],
            },
        ),
    ]
