# Generated by Django 5.1.15 on 2026-02-15 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAgreementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='agreement_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('returning', 'Returning'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='rentalagreement',
            index=models.Index(fields=['direction', 'status'], name='rentals_ren_directi_cc835d_idx'),
        ),
        migrations.AddField(
            model_name='rentalagreementline',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rentals.rentalagreement'),
        ),
        migrations.AddField(
            model_name='rentalagreementline',
            name='equipment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_agreement_lines', to='equipment.equipmentmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='rentalagreementline',
            unique_together={('agreement', 'equipment_model')},
        ),
    ]
