# Generated by Django 5.1.15 on 2026-02-15 16:22

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('schedules', '0001_initial'),
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('checked_out_at', models.DateTimeField()),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_returned', models.PositiveIntegerField(default=0)),
                ('condition_on_return', models.CharField(blank=True, max_length=20)),
                ('return_notes', models.TextField(blank=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_transferred', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-checked_out_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_planned', models.PositiveIntegerField()),
                ('is_over_allocated', models.BooleanField(default=False)),
                ('over_allocation_note', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['equipment_model__category', 'equipment_model__name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='has_conflicts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['schedule_type', 'status'], name='schedules_s_schedul_ddd10c_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='schedules_s_start_d_edefb3_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['parent'], name='schedules_s_parent__7ea7e9_idx'),
        ),
        migrations.AddField(
            model_name='checkoutrecord',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkoutrecord',
            name='checked_out_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkoutrecord',
            name='equipment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_records', to='equipment.equipmentitem'),
        ),
        migrations.AddField(
            model_name='checkoutrecord',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_records', to='transfers.equipmenttransfer'),
        ),
        migrations.AddField(
            model_name='scheduleequipment',
            name='equipment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_allocations', to='equipment.equipmentmodel'),
        ),
        migrations.AddField(
            model_name='scheduleequipment',
            name='planned_items',
            field=models.ManyToManyField(blank=True, related_name='planned_in_schedules', to='equipment.equipmentitem'),
        ),
        migrations.AddField(
            model_name='scheduleequipment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_allocations', to='schedules.schedule'),
        ),
        migrations.AddField(
            model_name='checkoutrecord',
            name='schedule_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_records', to='schedules.scheduleequipment'),
        ),
        migrations.AddField(
            model_name='schedulestatuslog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulestatuslog',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='schedules.schedule'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleequipment',
            unique_together={('schedule', 'equipment_model')},
        ),
        migrations.AddConstraint(
            model_name='checkoutrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('checked_in_at__isnull', True), ('equipment_item__isnull', False), ('transferred_at__isnull', True)), fields=('equipment_item',), name='unique_active_checkout_per_item'),
        ),
        migrations.AddConstraint(
            model_name='checkoutrecord',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_returned__lte', django.db.models.expressions.CombinedExpression(models.F('quantity'), '-', models.F('quantity_transferred')))), name='checkout_quantity_consistency'),
        ),
    ]
