# Generated by Django 5.1.15 on 2026-02-15 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'Multi-Select')], max_length=20)),
                ('entity_type', models.CharField(choices=[('equipment_model', 'Equipment Model'), ('equipment_item', 'Equipment Item')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('options', models.JSONField(blank=True, help_text='For SELECT/MULTISELECT: [{"value":"dmx","label":"DMX"}]', null=True)),
                ('validation_rules', models.JSONField(blank=True, help_text='e.g., {"min":0,"max":100}', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_filterable', models.BooleanField(default=False)),
                ('is_visible_in_list', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='If set, this field only applies to this category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='equipment.equipmentcategory')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('slug', 'entity_type')},
            },
        ),
    ]
