# Generated by Django 5.1.15 on 2026-02-15 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='schedules.schedule')),
                ('to_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='schedules.schedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
