# Generated by Django 5.1.15 on 2026-02-15 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('schedules', '0002_checkoutrecord_scheduleequipment_schedulestatuslog_and_more'),
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='equipmenttransfer',
            name='transferred_at',
        ),
        migrations.AddField(
            model_name='equipmenttransfer',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmenttransfer',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmenttransfer',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmenttransfer',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmenttransfer',
            name='planned_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='equipmenttransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_schedule', models.F('to_schedule')), _negated=True), name='transfer_no_self_transfer'),
        ),
        migrations.AddField(
            model_name='transferlineitem',
            name='equipment_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_line_items', to='equipment.equipmentitem'),
        ),
        migrations.AddField(
            model_name='transferlineitem',
            name='equipment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_line_items', to='equipment.equipmentmodel'),
        ),
        migrations.AddField(
            model_name='transferlineitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='transfers.equipmenttransfer'),
        ),
    ]
